### ISSUE TITLE
Sentence detection breaks URLs

### ISSUE THREAD

**Issue by martinpub** [mtmse/pipeline#2]
Using `--sentence-detection` or `--tts` on epub3-to-epub3 it seems the sentence detection breaks URLs.

Sample input:
```
<p><em>En fullständig lista över titlar utgivna i FOKK&#x002D;serien finns på: <a href="http://www.kkrva.se/?page&#x005F;id&#x003D;715">http://www.kkrva.se/?page&#x005F;id&#x003D;715</a></em></p>
```
Resulting output:
```
<p><em><span id="st4-3">En fullständig lista över titlar utgivna i FOKK-serien finns på: <a href="http://www.kkrva.se/?page_id=715">http://www.kkrva.se/?</a></span><a href="http://www.kkrva.se/?page_id=715"><span id="st4-4">page_id=715</span></a></em></p>
```

The desired result should be never to break URLs with sentence spans, i.e. ignoring potentially triggering punctuation inside URLs. Note that this is probably a good idea not only for URLs occurring as link text, but also for other text content (e.g. non-linked) starting with "http://", "https://" or similar.

Comment from @bertfrees:

> Yes, this requires tweaking of the lexer algorithm. I'm not very familiar with that code, but I believe the appropriate place to do this is modules/nlp/nlp-common/src/main/java/org/daisy/pipeline/nlp/ruledcategorizers/RuledMultilangCategorizer.java

**Comment by bertfrees** [comment]
To be clear, this happens also without  `--sentence-detection true` and with `--tts true`, right?

**Comment by martinpub** [comment]
Yes, I double checked my command issued and it did not include the (redundant) sentence detection option, only tts.

**Comment by martinpub** [comment]
Hi @kalaspuffar and @carl-textalk. In today's test on the MTM Azure server, I still get the broken output:

> `<p xml:lang="sv" lang="sv"><em><span id="st3-24" class="sentence">En fullständig lista över titlar utgivna i FOKK-serien finns på: <a href="http://www.kkrva.se/?page_id=715">http://www.kkrva.se/?</a></span><a href="http://www.kkrva.se/?page_id=715"><span id="st3-25" class="sentence">page_id=715</span></a></em></p>`

Can you look into it?

**Comment by kalaspuffar** [comment]
Hi @martinpub 

Is this failure on the machine deployed by Eric with the most current tag or the test machine mtm-pipe2 that I tried to update?

Best regards
Daniel

**Comment by martinpub** [comment]
Sorry for the confusion @kalaspuffar, it is mtm-pipe2. @fredrikschill verified that it was updated according to the latest release tag, but perhaps it was not succesful?

**Comment by kalaspuffar** [comment]
Hi @martinpub 

I have installed a deb package that we built using the latest tag. I don't have any way to verify so I could not be sure if it actually worked.

Best regards
Daniel

**Comment by martinpub** [comment]
OK. dp2 version gives "Pipeline version: 1.14.3-SNAPSHOT", but perhaps this tag was not updated with the release?

Looking at files, it looks like e.g. /opt/daisy-pipeline2/bin/pipeline2 was updated on May 7.

**Comment by martinpub** [comment]
BTW @kalaspuffar, was this the first release deployed including the legal document feature? I can see that a legal document was added when testing, so this might be a clue.

**Comment by kalaspuffar** [comment]
Hi @martinpub 

We have now rebuilt the package again and verified that the newly added charset files from Carl is present at least. We have built from the tag on our development machine and got a new package. 

After that I stopped the service on the test machine and deployed the package again with 

```
dpkg -i pipeline2-1.14.3-SNAPSHOT_debian.deb 
```

It should now be up and running again. Please try again and see if you can get it to work. I will set up a local Debian guest and try to install the package there in order to see if I can verify the package contents.

Best regards
Daniel

**Comment by martinpub** [comment]
Hi @kalaspuffar,

Thank you very much! In running this again after your manoeuvre, the broken URLs problem is fixed.
