### ISSUE TITLE
Headings upgraded from aria-labels do not get proper level

### ISSUE THREAD

**Issue by martinpub** [mtmse/pipeline#3]
There is a mechanism for upgrading aria-labels in source documents to "real" headings using epub3-to-epub3's `--ensure-section-headings` option.

Currently, there seems to be an issue with the heading levels, resulting in e.g.:

```
<section aria-labelledby="aria_label_1" ns2:type="cover" id="id_1">
<h1 id="aria_label_1"><span id="st1-1">Omslag</span></h1
<section aria-labelledby="aria_label_2" class="frontcover" id="prodnote_1">
<h1 id="aria_label_2"><span id="st1-2">Framsida</span></h1>
[...]
```

This, despite the second heading is a second-level heading in the navigation document toc:

```
<h1 id="n1">Contents</h1>
<ol class="plain">
<li><a href="DTB37628-001-cover.xhtml#level1_1">Omslag</a>
<ol class="plain">
<li><a href="DTB37628-001-cover.xhtml#prodnote_1">Framsida</a></li>
[...]
```

**Comment by martinpub** [comment]
(@bertfrees will have a look.)

**Comment by bertfrees** [comment]
This is fixed (not deployed yet).

**Comment by martinpub** [comment]
Yay!

**Comment by martinpub** [comment]
Verified fixed, thanks @bertfrees!
