### ISSUE TITLE
Unexpected fail in epub3-to-epub3 metadata injection job

### ISSUE THREAD

**Issue by martinpub** [mtmse/pipeline#37]
### Expected Behavior
Updating an EPUB 3 file with the metadata injection function in epub3-to-epub3.

### Actual Behavior
Failing job with output:

> `A sequence of more than one item is not allowed as the value of variable $from-nav (<d:anchor/>, <d:anchor/>)  (Please see detailed log for more info.)`

### Steps to Reproduce
1. Run metadata injection job according to the attached API job request on the attached file.

### Details
The logs point at this error:

> ```
> 2021-07-29 09:26:15,623 [ERROR] org.daisy.pipeline.job.Job - job finished with error state
> A sequence of more than one item is not allowed as the value of variable $from-nav (<d:anchor/>, <d:anchor/>) 
> 	at xsl:variable/@select(label-pagebreaks-from-nav.xsl:31)
> 	at xsl:apply-templates processing /html/body[1]/section[1]/div[1](label-pagebreaks-from-nav.xsl:45)
> 	at xsl:apply-templates processing /html/body[1]/section[1](label-pagebreaks-from-nav.xsl:45)
> 	at xsl:apply-templates processing /html/body[1](label-pagebreaks-from-nav.xsl:45)
> 	at xsl:apply-templates processing /html(label-pagebreaks-from-nav.xsl:22)
> 	at {http://www.w3.org/ns/xproc}xslt(label-pagebreaks-from-nav.xpl:137)
> 	at label-pagebreaks-from-nav.xpl:134
> 	at label-pagebreaks-from-nav.xpl:121
> 	at label-pagebreaks-from-nav.xpl:111
> 	at {http://www.daisy.org/ns/pipeline/xproc}epub3-label-pagebreaks-from-nav(epub3-to-epub3.convert.xpl:615)
> 	at epub3-to-epub3.convert.xpl:606
> ```

The label-pagebreaks-from-nav function does not sound like something we intend to call here, not sure what this means? The metadata injection should not touch pagebreaks whatsoever.

### Environment
MTM production system, Pipeline built from https://github.com/mtmse/pipeline/releases/tag/20210630

### Logs
https://gist.github.com/martinpub/17694e61b99d573e0815b781d03f78fa

**Comment by martinpub** [comment]
Hi @bertfrees! Any ideas why this job fails like this? Let me know if you need the source EPUB to troubleshoot and I will send it separately.

**Comment by bertfrees** [comment]
Hi Martin. Please send me the EPUB.

The EPUB 3 enhancer script performs page number fixes (adding `epub:type` and `role`) regardless of which options are specified.

**Comment by martinpub** [comment]
Thanks @bertfrees, have emailed you privately the EPUB.

**Comment by bertfrees** [comment]
Thanks. The error appears to be caused by a page number listed twice in the navigation document:

```xml
<li><a href="V000036-023-chapter.xhtml#page-177">177</a></li>
<li><a href="V000036-023-chapter.xhtml#page-177">177</a></li>
```

I have fixed the bug in the script, but now you also know how to work around it.

**Comment by martinpub** [comment]
Thank you very very much @bertfrees for spotting this error in the book, as well as fixing the bug. I have updated the book now and it should run just fine.
