### ISSUE TITLE
Sentence detection is broken around noteref links

### ISSUE THREAD

**Issue by martinpub** [mtmse/pipeline#5]
Using --sentence-detection on epub3-to-epub3 it seems the sentence detection is broken around noteref links.

Sample output:

`<span id="st11-649">Regeringen underströk att en realistisk plan i ekonomisk balans är en förutsättning för att den fortsatta ominriktningen skall kunna genomföras i enlighet med propositionen.<a role="doc-noteref" ns2:type="noteref" id="c04090_1" href="#c04090">90</a> Osäkerheter i ekonomiskt hänseende måste därför följas noggrant.</span>`

Desired result would be:

`<span id="st11-649">Regeringen underströk att en realistisk plan i ekonomisk balans är en förutsättning för att den fortsatta ominriktningen skall kunna genomföras i enlighet med propositionen.</span><a role="doc-noteref" ns2:type="noteref" id="c04090_1" href="#c04090">90</a> <span id="st11-650">Osäkerheter i ekonomiskt hänseende måste därför följas noggrant.</span>`

Comment from @bertfrees:

> There's a period before the "90" which is not regarded as the end of a sentence. I'm guessing this does not have to do with the noteref element, but with the fact that there is no space between "." and "90". The reason why a pagebreak element is treated specially is to make it skippable, and I guess also to make it not affect the pronunciation of the sentence if the pagebreak happens in the middle of the sentence. But if I'm not mistaken it does not have an influence on the sentence/word detection. But anyway, let's try it [isolating the noteref elements before applying to TTS] and see what happens. It might at least have a positive effect on the pronunciation.

**Comment by bertfrees** [comment]
I said:

> I'm guessing this does not have to do with the noteref element, but with the fact that there is no space between "." and "90".

This is indeed one reason, but actually there are more issues. Even with a space after the first sentence, it does not get a separate span unless the next character is a letter. Whether or not there are `<a>` elements does not matter.

**Comment by kalaspuffar** [comment]
Hi @martinpub 

We have discussed this issue with @bertfrees, and we have concluded that this is a way to solve this issue, and it was not that complicated.

Currently, this solution will create three sentences because it will always separate note references into their own sentences. I thought this was a reasonable solution because you usually pause between reading some text and then inform about where to read more about this topic.

In this issue and during a meet with Bert, we discussed that you could also create a solution where you specify in CSS, for instance, that note references should not be visible, and that means that they will not be read, and then the sentence detection should work fine as well. 

This is a little more complicated solution as there is no implementation for the CSS parser today to remove information from the document generally.

So our question here is if this solution will suffice or if we need to look into another perhaps more involved solution?

Best regards
Daniel

**Comment by martinpub** [comment]
Hi @kalaspuffar,

Thanks for the update. Just to make sure, by three sentences, you mean that a sentence span will be added to the noteref link in my example above?

We are not interested in removing note references from being read or displayed on the screen, so I think this will do. What we might be interested in however is to adjust pauses related to the note reference, but as I understand it, Pipeline 2 is already prepared to handle pause-related CSS. Hopefully CSS pause rules takes precedence over default pauses sent by Pipeline 2 to the TTS.

To be completely sure, I have to check it in the talking book software as well, but I think it will be alright. Will get back to you.

**Comment by bertfrees** [comment]
> This is a little more complicated solution as there is no implementation for the CSS parser today to remove information from the document generally.

To be clear: today we can indeed not remove note references from being spoken or displayed on screen, but the other solution does not depend on that. The other solution only requires that pauses are inserted not only in between sentences, but also before and after noterefs (and page numbers and other similar elements). This could be done with CSS (already possible today) or it could be done by default, or both (default with possibility to overwrite pause lengths with CSS).

> Hopefully CSS pause rules takes precedence over default pauses sent by Pipeline 2 to the TTS.

Depends on what you mean exactly. It can be implemented in such a way that the pause lengths before/after noterefs can be overwritten with CSS. However the pauses before/after noterefs and the pauses between sentences are two separate things. The pauses in between sentences are created by the TTS adapter (this is the case for CereProc) or by the TTS engine itself if it encounters a period. Pauses that you specify with CSS will be added on top of these. If we need pauses before/after noterefs to "collapse" with the pauses between sentences we'll need some special handling.

**Comment by martinpub** [comment]
Thanks for your comments @bertfrees. I think this is an issue for testing. But as I understand the discussion above, the implementation suggested is the noterefs will always be contained in/contain a separate sentence.

I'm still checking regarding the talking book software, so @kalaspuffar will let you know when I have verified this solution will work.

A follow-up question to you @bertfrees, are the sentence pauses in the TTS adapter currently hard coded for CereProc? Or are they configurable in tts config?

**Comment by bertfrees** [comment]
It's hard coded (250ms). It can't be configured. But actually I just added the pause without actually verifying whether CereProc already adds pauses (without sending it `ssml:break`). Let me know if you think the pauses should be longer or shorter.

**Comment by martinpub** [comment]
Great, thanks for confirming. Will let you know what the tests show, but good to know how it's currently set up!

**Comment by martinpub** [comment]
@kalaspuffar I have tested this in the talking book software, using these two examples:

```
      <p><span id="st3-18" class="sentence">This is a paragraph where an end-of-sentence footnote is used.</span><span id="sttest-1" class="sentence"><a role="doc-noteref" epub:type="noteref" id="intext_noteref-1" href="#intext_note-1">*</a></span> <span id="sttest-2" class="sentence">This is the following sentence.</span></p>

      <p><span id="st3-19" class="sentence">In this second paragraph, an endnote reference is being used instead.</span><a role="doc-noteref" epub:type="noteref" id="endnote_noteref-1" href="sytbtest001-003-endnotes.xhtml#endnote-1"><span id="sttest-3">1</span></a> <span id="sttest-4" class="sentence">This is also followed by a sentence.</span></p>
```
It seems the first variant creates an extra step when moving from synchronisation point to synchronisation point during narration, I guess the program hangs on to both the a and the span elements there.

The following is preferable but I think there was some complication?

`<p><span id="st3-18" class="sentence">This is a paragraph where an end-of-sentence footnote is used.</span><a role="doc-noteref" epub:type="noteref" id="intext_noteref-1" href="#intext_note-1">*</a> <span id="sttest-2" class="sentence">This is the following sentence.</span></p>`

I also noted some validation issues after sentence detection, but that is a separate issue, just wanted to confirm that the above solution will work in talking book software.

**Comment by martinpub** [comment]
Tested and verified.
