### ISSUE TITLE
Sentence detection marks up `<sub>` elements as sentences

### ISSUE THREAD

**Issue by martinpub** [mtmse/pipeline#6]
Sample output:

`<p><span id="st11-23">Varning för pandemi (H</span><sub><span id="st11-24">1</span></sub><span id="st11-25">N</span><sub><span id="st11-26">1</span></sub><span id="st11-27">,"svininfluensan").</span></p>`

Desired result:

`<p><span id="st11-23">Varning för pandemi (H<sub>1</sub>N<sub>1</sub>,"svininfluensan").</span></p>`

Comment from @bertfrees:

> Good catch. I'll fix it (in modules/nlp/html-break-detection/src/main/resources/xml/library.xpl).

**Comment by bertfrees** [comment]
This is fixed (not deployed yet).

**Comment by martinpub** [comment]
Yay! Looking forward to testing it. Thanks!

**Comment by martinpub** [comment]
Verified fixed, thanks @bertfrees!
